require('./utils.test.js');
require('./otherplugins.test.js');
require('./agencyplugins.test.js');
require('./candidateplugins.test.js');
require('./clientplugins.test.js');
//require('./interview.test.js');
require('./harensstalent.test.js');
require('./adminplugins.test.js');
require('./redis.test.js');