const Vision		 = require('vision');
const Blipp 		 = require('blipp');
const Inert 		 = require('inert');

const Candidate 		  = require('./plugins/candidate.js');
const Client				  = require('./plugins/client.js');
const Login 				  = require('./plugins/login.js');
const ClientSignUp    = require('./plugins/clientsignup.js');
const Home 					  = require('./plugins/home.js');
const AdminDashboard  = require('./plugins/admindashboard.js');
const Logout			    = require('./plugins/logout.js');
const AdminVacancies  = require('./plugins/adminvacancies.js');
const ApproveUsers    = require('./plugins/approveusers.js');
const UserInfo        = require('./plugins/userinfo.js');
const AgencyLogin     = require('./plugins/agencylogin.js');
const Agency          = require('./plugins/agency.js');
const AgencySignUp    = require('./plugins/agencysignup.js');
const Resources       = require('./plugins/resources.js');
const ApproveUser     = require('./plugins/approveuser.js');
const SubmitJob       = require('./plugins/submitjob.js');
const ClientJob       = require('./plugins/clientjob.js');
const AgencyJob       = require('./plugins/agencyjob.js');
const AdminJob        = require('./plugins/adminjob.js');
const SignS3		      = require('./plugins/signs3.js');
const SubmitVacancyCV = require('./plugins/submitvacancycv.js');
const AgencyMyJobs    = require('./plugins/agencymyjobs.js');
const SubmitCandidate = require('./plugins/submitcandidate.js');

module.exports = [Blipp, Inert, Vision, Home, Login, Candidate, Client, ClientSignUp, AdminDashboard, Logout, AdminVacancies, ApproveUsers, ApproveUser, UserInfo, AgencyLogin, Agency, AgencySignUp, Resources, SubmitJob, ClientJob, AgencyJob, AdminJob, SignS3, SubmitVacancyCV, AgencyMyJobs, SubmitCandidate];
